# Generated by Django 5.1.7 on 2025-03-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Administrator laboratorije'), ('quality', 'Kontrolor kvaliteta'), ('staff', 'Osoblje'), ('viewer', 'Pregled')], default='staff', max_length=20, verbose_name='Uloga'),
        ),
    ]
