# Generated by Django 5.1.7 on 2025-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='code',
            field=models.CharField(max_length=2, unique=True, verbose_name='Šifra centra'),
        ),
        migrations.AlterField(
            model_name='center',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Naziv centra'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Naziv laboratorije'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Šifra'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Naziv'),
        ),
    ]
