# Generated by Django 5.1.7 on 2025-03-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_customuser_role'),
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv ovlašćenja')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Naziv radnog mesta')),
                ('code', models.CharField(max_length=20, verbose_name='Broj radnog mesta')),
                ('job_type', models.CharField(choices=[('research', 'Istraživačka radna mesta'), ('technical', 'Radna mesta za obavljanje stručnih tehničkih poslova')], max_length=50, verbose_name='Tip radnog mesta')),
                ('subcategory', models.CharField(blank=True, max_length=255, verbose_name='Podkategorija')),
                ('process_description', models.TextField(blank=True, help_text='Odvojite tačke novim redom', verbose_name='Opis radnog procesa')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=255, verbose_name='Prezime')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Datum rođenja')),
                ('place', models.CharField(max_length=255, verbose_name='Mesto')),
                ('jmbg', models.CharField(max_length=13, unique=True, verbose_name='JMBG')),
                ('education_level', models.CharField(max_length=255, verbose_name='Stepen obrazovanja')),
                ('school', models.CharField(max_length=255, verbose_name='Škola')),
                ('academic_title', models.CharField(max_length=255, verbose_name='Akademska titula')),
                ('scientific_title', models.CharField(max_length=255, verbose_name='Naučno zvanje')),
                ('start_date_in_profession', models.DateField(blank=True, null=True, verbose_name='Početak rada u struci')),
                ('start_date_in_ims', models.DateField(blank=True, null=True, verbose_name='Početak rada u IMS')),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.laboratory', verbose_name='Organizaciona celina')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField(blank=True, verbose_name='Stručno iskustvo')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Zaposleni')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipInInternationalOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255, verbose_name='Naziv organizacije')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Zaposleni')),
            ],
        ),
        migrations.CreateModel(
            name='StaffJobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Datum početka')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Datum završetka')),
                ('job_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.jobposition', verbose_name='Radno mesto')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Zaposleni')),
            ],
            options={
                'verbose_name': 'Radno mesto zaposlenog',
                'verbose_name_plural': 'Radna mesta zaposlenih',
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('Obuka za obavljanje radnih zadataka', 'Obuka za obavljanje radnih zadataka'), ('Stručno usavršavanje', 'Stručno usavršavanje'), ('Obuka za sistem menadžmenta', 'Obuka za sistem menadžmenta'), ('Specijalistička obuka', 'Specijalistička obuka')], default='Laboratorija', max_length=50, verbose_name='Vrsta obuke')),
                ('training_name', models.TextField(help_text='Odvojite tačke novim redom', max_length=250, verbose_name='Naziv obuke')),
                ('location', models.CharField(max_length=255, verbose_name='Mesto održavanja obuke')),
                ('start_date', models.DateField(verbose_name='Datum početka obuke')),
                ('end_date', models.DateField(verbose_name='Datum završetka obuke')),
                ('instructors_other', models.TextField(blank=True, null=True, verbose_name='Nosilac obuke - Ostali')),
                ('training_material', models.TextField(blank=True, null=True, verbose_name='Materijal za obuku')),
                ('document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Naziv dokumenta koji potvrđuje uspešnost obuke')),
                ('training_effectiveness', models.TextField(blank=True, null=True, verbose_name='Vrednovanje efektivnosti obuke')),
                ('report', models.FileField(blank=True, null=True, upload_to='trainings/', verbose_name='Izveštaj sa obuke')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='Datum izveštaja')),
                ('r_b_z', models.CharField(blank=True, max_length=255, null=True, verbose_name='R.b.z.')),
                ('instructors', models.ManyToManyField(blank=True, related_name='instructed_trainings', to='staff.staff', verbose_name='Nosilac obuke - Zaposleni')),
                ('laboratory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.laboratory', verbose_name='Laboratorija')),
                ('methods', models.ManyToManyField(blank=True, to='methods.method', verbose_name='Metode')),
                ('report_submitted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to='staff.staff', verbose_name='Izveštaj podneo')),
                ('staff', models.ManyToManyField(related_name='attended_trainings', to='staff.staff', verbose_name='Zaposleni')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_course', models.TextField(blank=True, verbose_name='Obuke/Usavršavanja')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Zaposleni')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.FileField(blank=True, null=True, upload_to='staff_test_results/', verbose_name='Test (PDF)')),
                ('method', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='methods.method', verbose_name='Metoda')),
                ('staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Zaposleni')),
            ],
        ),
        migrations.CreateModel(
            name='Authorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum dodele ovlašćenja')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methods.method', verbose_name='Metoda')),
                ('authorization_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.authorizationtype', verbose_name='Ovlašćenje')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Zaposleni')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('staff', 'method', 'authorization_type'), name='unique_authorization')],
            },
        ),
        migrations.CreateModel(
            name='StaffMethodTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methods.method')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.training')),
            ],
            options={
                'unique_together': {('staff', 'method', 'training')},
            },
        ),
    ]
