# Generated by Django 5.1.7 on 2025-03-26 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='staff/trainings/', verbose_name='Izveštaj sa obuke'),
        ),
        migrations.AlterField(
            model_name='trainingtests',
            name='test',
            field=models.FileField(blank=True, null=True, upload_to='staff/staff_test_results/', verbose_name='Test (PDF)'),
        ),
        migrations.CreateModel(
            name='NoMethodAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization', models.CharField(max_length=255, verbose_name='Naziv ovlašćenja')),
                ('date', models.DateField(verbose_name='Datum dodele ovlašćenja')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff', verbose_name='Zaposleni')),
            ],
        ),
    ]
