# Generated by Django 5.1.7 on 2025-03-24 07:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=255, verbose_name='Broj kartona')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv opreme')),
                ('scope', models.CharField(max_length=255, verbose_name='Opseg/Tačnost')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='Proizvođač')),
                ('type', models.CharField(max_length=255, verbose_name='Tip')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('serial_number', models.CharField(max_length=255, verbose_name='Serijski broj')),
                ('inventory_number', models.CharField(max_length=255, verbose_name='Inventarski broj')),
                ('purchase_date', models.DateField(verbose_name='Datum nabavke')),
                ('usage_start_date', models.DateField(verbose_name='Datum stavljanja u upotrebu')),
                ('location', models.CharField(max_length=255, verbose_name='Lokacija opreme')),
                ('other', models.TextField(max_length=255, verbose_name='Ostale bitne karakteristike')),
                ('equipment_type', models.CharField(choices=[('Glavna', 'Glavna'), ('Pomocna', 'Pomocna')], default='Glavna', max_length=7, verbose_name='Glavna/Pomoćna')),
                ('group', models.CharField(blank=True, choices=[('Termometri', 'Termometri'), ('Komparateri', 'Komparateri'), ('Vage', 'Vage'), ('Manometri', 'Manometri'), ('Transdjuseri', 'Transdjuseri'), ('Aparati', 'Aparati'), ('Merni prsten', 'Merni prsten'), ('Ostalo', 'Ostalo')], max_length=20, null=True, verbose_name='Grupa')),
                ('is_rashodovana', models.BooleanField(default=False, editable=False, verbose_name='Rashodovana')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ManyToManyField(related_name='equipment', to='core.laboratory', verbose_name='Laboratorija')),
                ('main_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_equipments', to='equipment.equipment', verbose_name='Glavna oprema')),
                ('responsible_laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_equipment', to='core.laboratory', verbose_name='Odgovorna laboratorija')),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibration_date', models.DateField(blank=True, null=True, verbose_name='Datum etaloniranja')),
                ('certificate_number', models.CharField(max_length=255, unique=True, verbose_name='Broj uverenja o etaloniranju')),
                ('calibration_laboratory', models.CharField(blank=True, max_length=255, verbose_name='Laboratorija za etaloniranje')),
                ('calibration_range', models.CharField(blank=True, max_length=255, verbose_name='Opseg etaloniranja')),
                ('measurement_uncertainty', models.CharField(blank=True, max_length=255, verbose_name='Merna nesigurnost')),
                ('certificate', models.FileField(blank=True, upload_to='certificates/', verbose_name='Uverenje o etaloniranju')),
                ('calibration_interval', models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Interval etaloniranja')),
                ('next_calibration_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Datum ponovnog etaloniranja')),
                ('equipment_age', models.FloatField(blank=True, editable=False, null=True, verbose_name='Starost opreme')),
                ('frequency_of_use', models.CharField(choices=[('Nekoliko puta mesecno', 'Nekoliko puta mesecno'), ('Nekoliko puta nedeljno', 'Nekoliko puta nedeljno'), ('Svakodnevno', 'Svakodnevno')], max_length=30, verbose_name='Učestalost korišćenja opreme')),
                ('conditions_of_use', models.CharField(choices=[('Kontrolisani lab. uslovi', 'Kontrolisani lab. uslovi'), ('Nekontrolisani lab. uslovi', 'Nekontrolisani lab. uslovi'), ('Korišćenje van lab.', 'Korišćenje van lab.')], max_length=30, verbose_name='Uslovi korišćenja i čuvanja')),
                ('measurement_uncertainty_tracking', models.CharField(choices=[('Opadanje MN', 'Opadanje MN'), ('Konstantna MN', 'Konstantna MN'), ('Rast MN', 'Rast MN')], max_length=30, verbose_name='Praćenje merne nesigurnosti')),
                ('required_accuracy', models.CharField(choices=[('Nema zahtevanih propisa', 'Nema zahtevanih propisa'), ('Standardni nivo tačnosti', 'Standardni nivo tačnosti'), ('Visok nivo tačnosti', 'Visok nivo tačnosti')], max_length=30, verbose_name='Zahtevana tačnost merenja')),
                ('recommended_calibration_interval', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Preporučeni interval etaloniranja')),
                ('mandatory_calibration_interval', models.PositiveIntegerField(blank=True, null=True, verbose_name='Produženi period etaloniranja')),
                ('pie_document_link', models.CharField(blank=True, max_length=100, verbose_name='PIE veza sa dokumentom')),
                ('calibration_note', models.TextField(blank=True, max_length=500, verbose_name='Napomena o etaloniranju')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='InternalControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Naziv interne kontrole')),
                ('last_control_date', models.DateField(verbose_name='Datum poslednjeg IK')),
                ('control_interval', models.IntegerField(help_text='Interval u mesecima', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Interval IK (meseci)')),
                ('next_control_date', models.DateField(blank=True, editable=False, null=True, verbose_name='Datum ponovnog IK')),
                ('control_note', models.FileField(blank=True, upload_to='certificates/', verbose_name='Zapis o IK')),
                ('note', models.TextField(blank=True, max_length=500, null=True, verbose_name='NAPOMENA')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('controlling_devices', models.ManyToManyField(blank=True, related_name='controlling_internal_controls', to='equipment.equipment')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malfunction_date', models.DateField(verbose_name='Datum konstatovanja neispravnosti')),
                ('action_taken', models.TextField(verbose_name='Radnja pri kojoj je neispravnost utvrđena')),
                ('malfunction_description', models.TextField(verbose_name='Opis neispravnosti')),
                ('resolved_within_institute', models.CharField(choices=[('Istitut IMS', 'Istitut IMS'), ('Spoljni servis', 'Spoljni servis')], default='Istitut IMS', max_length=20, verbose_name='Neispravnost otklonjena u')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Napomena')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
            ],
        ),
    ]
