# Generated by Django 5.1.7 on 2025-03-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_calibrated',
            field=models.BooleanField(default=True, verbose_name='Da li se kalibriše'),
        ),
    ]
