# Generated by Django 5.1.7 on 2025-03-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_equipment_is_calibrated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='is_calibrated',
            field=models.BooleanField(choices=[(True, 'Da'), (False, 'Ne')], default=True, verbose_name='Da li se kalibriše'),
        ),
    ]
