# Generated by Django 5.1.7 on 2025-04-08 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_calibration_certificate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqipmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv grupe')),
                ('description', models.TextField(blank=True, max_length=255, verbose_name='Opis grupe')),
            ],
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='group',
        ),
    ]
