# Generated by Django 5.1.7 on 2025-04-08 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_eqipmentgroup_remove_equipment_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EqipmentGroup',
            new_name='EquipmentGroup',
        ),
        migrations.AddField(
            model_name='equipment',
            name='equipment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipments', to='equipment.equipmentgroup', verbose_name='Grupa opreme'),
        ),
    ]
