# Generated by Django 5.1.7 on 2025-03-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='methoddocumentation',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methods.method', verbose_name='Metoda'),
        ),
    ]
