# Generated by Django 5.1.7 on 2025-03-31 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_center_code_alter_center_name_and_more'),
        ('documents', '0002_initial'),
        ('equipment', '0004_alter_calibration_certificate_and_more'),
        ('methods', '0002_alter_standard_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_record', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.laboratory')),
                ('related_equipment', models.ManyToManyField(blank=True, to='equipment.equipment')),
                ('related_methods', models.ManyToManyField(blank=True, to='methods.method')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('issued_date', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('change_description', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('viewed', 'Pregledano'), ('downloaded', 'Preuzeto')], max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentversion')),
            ],
        ),
    ]
