# Generated by Django 5.1.7 on 2025-03-31 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documenttype_document_documentversion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documentation',
        ),
        migrations.DeleteModel(
            name='MethodDocumentation',
        ),
    ]
