# Generated by Django 5.1.7 on 2025-04-01 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_center_code_alter_center_name_and_more'),
        ('documents', '0004_delete_documentation_delete_methoddocumentation'),
        ('equipment', '0004_alter_calibration_certificate_and_more'),
        ('methods', '0002_alter_standard_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumenti'},
        ),
        migrations.AlterModelOptions(
            name='documentaccesslog',
            options={'verbose_name': 'Pristup dokumentu', 'verbose_name_plural': 'Pristupi dokumentima'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Tip dokumenta', 'verbose_name_plural': 'Tipovi dokumenata'},
        ),
        migrations.AlterModelOptions(
            name='documentversion',
            options={'ordering': ['-issued_date'], 'verbose_name': 'Verzija dokumenta', 'verbose_name_plural': 'Verzije dokumenata'},
        ),
        migrations.AlterField(
            model_name='document',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Oznaka dokumenta'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja'),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivan'),
        ),
        migrations.AlterField(
            model_name='document',
            name='laboratory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.laboratory', verbose_name='Laboratorija'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_equipment',
            field=models.ManyToManyField(blank=True, to='equipment.equipment', verbose_name='Povezana oprema'),
        ),
        migrations.AlterField(
            model_name='document',
            name='related_methods',
            field=models.ManyToManyField(blank=True, to='methods.method', verbose_name='Povezane metode'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Naziv dokumenta'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='documents.documenttype', verbose_name='Tip dokumenta'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='access_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vreme pristupa'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='action',
            field=models.CharField(choices=[('viewed', 'Pregledano'), ('downloaded', 'Preuzeto')], max_length=50, verbose_name='Akcija'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documentversion', verbose_name='Verzija dokumenta'),
        ),
        migrations.AlterField(
            model_name='documentaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Korisnik'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='is_record',
            field=models.BooleanField(default=False, verbose_name='Da li je zapis'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Naziv tipa dokumenta'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='change_description',
            field=models.TextField(blank=True, verbose_name='Opis promene'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document', verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Fajl'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Trenutna verzija'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='issued_date',
            field=models.DateField(verbose_name='Datum izdavanja'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Postavio'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Važi do'),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='version_number',
            field=models.CharField(max_length=20, verbose_name='Broj verzije'),
        ),
    ]
