# Generated by Django 5.1.7 on 2025-03-24 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_customuser_role'),
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementUncertainty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=255, verbose_name='Naziv dokumenta')),
                ('uncertainty_value', models.CharField(max_length=50, verbose_name='Vrednost nesigurnosti')),
                ('calculation_date', models.DateField(verbose_name='Datum proračuna')),
                ('report_number', models.CharField(max_length=255, verbose_name='Broj izveštaja')),
                ('document', models.FileField(blank=True, null=True, upload_to='measurement_uncertainty/', verbose_name='Dokument')),
            ],
        ),
        migrations.CreateModel(
            name='PTScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizer', models.CharField(max_length=255, verbose_name='Organizator')),
                ('code_name', models.CharField(choices=[('ILC', 'ILC'), ('PT', 'PT'), ('EQA', 'EQA')], default='PT', max_length=10, verbose_name='Naziv ILC, PT ili EQA')),
                ('final_report', models.FileField(blank=True, null=True, upload_to='pt_schemes/', verbose_name='Završni izveštaj')),
                ('final_report_number', models.CharField(max_length=50, verbose_name='Broj završnog izveštaja')),
                ('final_report_date', models.DateField(verbose_name='Datum završnog izveštaja')),
                ('year', models.IntegerField(verbose_name='Godina')),
            ],
        ),
        migrations.CreateModel(
            name='PTSchemeMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participants', models.IntegerField(verbose_name='Broj učesnika')),
                ('z_score', models.TextField(blank=True, verbose_name='Z skor')),
                ('measures_taken', models.TextField(blank=True, verbose_name='Preuzete mere')),
            ],
        ),
        migrations.CreateModel(
            name='ControlTesting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(max_length=255, verbose_name='Broj izveštaja')),
                ('report_date', models.DateField(verbose_name='Datum izveštaja')),
                ('document', models.FileField(blank=True, null=True, upload_to='control_testing/', verbose_name='Dokument')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.laboratory', verbose_name='Laboratorija')),
            ],
        ),
        migrations.CreateModel(
            name='ControlTestingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_participants', models.IntegerField(verbose_name='Broj učesnika')),
                ('measures_taken', models.TextField(blank=True, verbose_name='Preuzete mere')),
                ('control_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quality.controltesting', verbose_name='Kontrolno ispitivanje')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methods.method', verbose_name='Metoda')),
            ],
        ),
    ]
