# Generated by Django 5.1.7 on 2025-03-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='methods/standards/', verbose_name='Dokument'),
        ),
    ]
